### ISSUE TITLE
Use Numpy arrays instead of pandas series for calculations

### ISSUE THREAD

**Issue by mir-cat** [mir-cat/BST234-FP#2]
Pandas series are much for user friendly and intuitive to work with. However, that friendliness comes at the cost of speed. Whenever possible, we should be looking to convert series to numpy arrays for speed of calculation

**Comment by mir-cat** [comment]
Matrix algebra seems especially faster with numpy arrays.

**Comment by katcorr** [comment]
Okay, here goes my first time trying to leave a Github comment  ... 
Yes, I think Chris noted a similar thing -- that numpy was faster than pandas.  Chris I thought you had started a branch for that, but I don't think I see one now so maybe I'm wrong?
TA DAH!

**Comment by mir-cat** [comment]
Converted everything to arrays
