### ISSUE TITLE
parallelize?

### ISSUE THREAD

**Issue by katcorr** [mir-cat/BST234-FP#6]
Hi -- I tried to see if I could parallelize the permutations, since they should be "embarassingly parallel" ... it doesn't seem to save much time, though ?  perhaps my code is inefficient?  or my computer ... ?  Anyways, I tried to add a branch in "parallelize" ... maybe one of you could see if it runs any faster with more threads on your computer?

**Comment by mir-cat** [comment]
Code is parallelize din the speedup-indices branch
