### ISSUE TITLE
Custom unweighted random sample code

### ISSUE THREAD

**Issue by mir-cat** [mir-cat/BST234-FP#7]
Right now the random sampling takes up about 95% of the total run time. If we can code up our own fast random sample, we will make huge speed gains.

**Comment by mir-cat** [comment]
An non-parallelized run on my laptop took ~500 seconds, of which ~440 was spent calculating random permutations

**Comment by chy530** [comment]
I tried replacing the return statement in permute_indices with: 

return np.random.random_integers(0, N-1, n)

and it seems to run a bit faster.

**Comment by mir-cat** [comment]
Speedup indices branch now has fast custom sampling code. It enables me to run all 10^7 samples with the processing pool in 11 minutes. However, the sampling function currently under samples at the tails so that needs to be fixed.

**Comment by mir-cat** [comment]
Sampling at the tails is now fixed, but either the 1s and 2s vector or the indices vector needs to be unshuffled.
